"""empty message

Revision ID: 04d78354dcf2
Revises: 
Create Date: 2020-01-15 20:50:35.881081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04d78354dcf2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blood_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=2), nullable=True),
    sa.Column('rh', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blood_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('blood_group_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('person_name', sa.String(length=256), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blood_group_id'], ['blood_group.id'], use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blood_request_timestamp'), 'blood_request', ['timestamp'], unique=False)
    op.create_table('donation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['donor_id'], ['user.id'], use_alter=True),
    sa.ForeignKeyConstraint(['request_id'], ['blood_request.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('blood_group_id', sa.Integer(), nullable=True),
    sa.Column('national_id', sa.String(length=20), nullable=True),
    sa.Column('last_donation_id', sa.Integer(), nullable=True),
    sa.Column('diseases', sa.String(length=1024), nullable=True),
    sa.Column('profile_setup', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['blood_group_id'], ['blood_group.id'], use_alter=True),
    sa.ForeignKeyConstraint(['last_donation_id'], ['donation.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('donation')
    op.drop_index(op.f('ix_blood_request_timestamp'), table_name='blood_request')
    op.drop_table('blood_request')
    op.drop_table('blood_group')
    # ### end Alembic commands ###
